version: '3.8'
services:
  db:
    image: postgres:16-bullseye
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=project_db
      - POSTGRES_PORT=5432
    ports:
      # Expose on different port to prevent conflict with local
      - '6543:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@project.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    depends_on:
      - db
    build: ./services/backend
    working_dir: /app
    restart: always
    ports:
      - '8000:8000'
    environment:
      - PROJECT_NAME=Project
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=project_db
      - DATABASE_URL=postgres://admin:admin@db/project_db
      - ROCKET_ADDRESS=0.0.0.0
    volumes:
      - ./services/backend/app:/app
      - /app/target/
    # command: sh -c "cargo watch -x 'run --release'"
    command: sh -c "cargo watch -x 'run'"

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
